from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('404/', views.page_not_found, name='err404'),
    path('500/', views.server_error, name='err500'),
    path('new/', views.new_post, name='new_post'),
    path('<int:post_id>/', views.post_view, name='post_view'),
    path('<int:post_id>/like/', views.like,
         name='like'),
    path('<int:post_id>/comments/', views.comments,
         name='comments'),
    path('<int:post_id>/comments/add_comment/', views.add_comment,
         name='add_comment'),
    path('my-comments/', views.my_comments,
         name='my_comments'),
    path('favourite/', views.favourite,
         name='favourite'),
    path('messages/', views.messages,
         name='messages'),
    path('messages/add_message/', views.add_message,
         name='add_message'),
    path('private-cabinet/', views.private_cabinet,
         name='private_cabinet'),
    path('post-management/', views.post_management,
         name='post_management'),
    path('post-management/<int:post_id>/delete/', views.post_delete,
         name='post_delete'),
    path('post-management/<int:post_id>/update/', views.post_update,
         name='post_update'),
    path('message-reply/', views.message_reply,
         name='message_reply'),
    path('message-reply/<int:chosen_user_id>/', views.message_reply,
         name='message_reply_id'),
    path('message-reply/<int:chosen_user_id>/add_reply/', views.add_reply,
         name='add_reply'),
    path('about/', views.about,
         name='about'),
]
