# Generated by Django 4.1.1 on 2022-09-29 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок статьи')),
                ('subheader', models.CharField(max_length=100, verbose_name='Подзаголовок статьи')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('modify_date', models.DateField(blank=True, null=True, verbose_name='Дата последних изменений')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Изображение')),
            ],
            options={
                'ordering': ('-pub_date', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('FROM_AUTHOR', 'From Author'), ('TO_AUTHOR', 'To Author')], max_length=11)),
                ('message_text', models.TextField(max_length=450, verbose_name='Текст комментария')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария')),
                ('interlocutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('interlocutor', 'send_time', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=450, verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='posts.post')),
            ],
            options={
                'ordering': ('post', 'created', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='posts.post')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('liker', 'favourite_post')},
            },
        ),
    ]
