# Generated by Django 4.1.1 on 2022-10-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subheader',
            field=models.CharField(max_length=150, verbose_name='Подзаголовок статьи'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Заголовок статьи'),
        ),
    ]
